# -*- coding: utf-8 -*-
"""Open-Meteo_APİ_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iCNaBSoLaR8aGn4PxYbhPM-JWqPm1P-P
"""

import requests
from datetime import datetime, timedelta
import pandas as pd
import matplotlib.pyplot as plt

# Open-Meteo API URL'si
base_url = 'https://api.open-meteo.com/v1/forecast'

# Gaziantep'in enlem ve boylam değerleri
latitude = 37.0662
longitude = 37.3833

# Son 2 günlük tarih aralığını belirleme
end_date = datetime.utcnow().date()
start_date = end_date - timedelta(days=2)

# API istek parametreleri
params = {
    'latitude': latitude,
    'longitude': longitude,
    'start_date': start_date,
    'end_date': end_date,
    'hourly': 'temperature_2m,relative_humidity_2m',
    'temperature_unit': 'celsius',
    'timezone': 'UTC'
}

# API'ye GET isteği gönder
response = requests.get(base_url, params=params)

# İsteğin başarılı olup olmadığını kontrol et
if response.status_code == 200:
    # JSON yanıtını ayrıştır
    data = response.json()
    temperatures = data['hourly']['temperature_2m']
    humidities = data['hourly']['relative_humidity_2m']
    times = data['hourly']['time']

    # Zamanları datetime formatına çevirme
    times = [datetime.fromisoformat(t) for t in times]

    # Verileri pandas DataFrame'e aktarma
    df = pd.DataFrame({
        'Zaman (UTC)': times,
        'Sıcaklık (°C)': temperatures,
        'Nemlilik (%)': humidities
    })

    # Tabloyu yazdırma
    print(df)

    # Sıcaklık ve nem verilerini görselleştirme
    fig, ax1 = plt.subplots(figsize=(12, 6))

    color = 'tab:red'
    ax1.set_xlabel('Zaman (UTC)')
    ax1.set_ylabel('Sıcaklık (°C)', color=color)
    ax1.plot(df['Zaman (UTC)'], df['Sıcaklık (°C)'], color=color)
    ax1.tick_params(axis='y', labelcolor=color)

    ax2 = ax1.twinx()
    color = 'tab:blue'
    ax2.set_ylabel('Nemlilik (%)', color=color)
    ax2.plot(df['Zaman (UTC)'], df['Nemlilik (%)'], color=color)
    ax2.tick_params(axis='y', labelcolor=color)

    plt.title(f"Gaziantep için Son 2 Günlük Sıcaklık ve Nemlilik Verileri")
    fig.tight_layout()
    plt.show()
else:
    print(f"Veri alınamadı: {response.status_code}")